FROM node:8.12.0-alpine as build

WORKDIR /app

COPY . .

RUN npm install node-sass@latest
RUN npm install
RUN npm run build -- --prod

FROM nginx:alpine

WORKDIR /app

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

## Remove default nginx website
RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]